### ISSUE TITLE
Automatically log out when appropriate

### ISSUE THREAD

**Issue by icidasset** [fission-codes/webnative#190]
1. When you sign out of the lobby, you should be signed out of all your apps.
2. For development, when switching environments, you should be logged out as well.

**Comment by bmann** [comment]
There are two ways to "log out" right now. There is "remove this device" and going to the nuke everything https://auth.fission.codes/reset/

I do that, and then create a fresh account. When I then go to Drive or Filecoin Backup App, I am surprised to see the old account still logged in. What is happening, is that the "old" UCAN is still active. It's like handing out an OAuth token from your Github or Twitter account to an app. Unless you actively log out or revoke those creds, the UCAN is valid ... until it hits a time out.

Drive has a sign out function, which solves that, but it can be confusing.

Filecoin Backup App does not have a sign out. So it's even MORE confusing, because I can't create a new account!

We're not expecting users to remove device or reset as part of "normal" operation. We do it all the time as part of testing. So we don't need to "optimize" for this. As well, shared desktop machines -- say, in a library or something -- could be a thing. Also not what we're optimizing for at this point.

So, here's my suggestion. Document (or default) that apps can set the expiry length. For Filecoin Backup App @bgins I would set this to 1 hour. We might want to set Drive to 1 hour as well?

Can one clear this in console with Webnative? Because as developers, we can do that too. Basically, I don't think we want to have all apps ALL have to do sign out functions, so in our own testing is there a way to go into console and see the username(s) and clear them, thus forcing a re-auth.

For (2), I'll leave that alone, I get that it might be annoying :P
