### ISSUE TITLE
Webnative Platform API request error

### ISSUE THREAD

**Issue by ha6755ad** [fission-codes/webnative#383]
# Summary
All calls to wn.apps[method]() are returning error 
index.jss:52          POST https://runfission.com/v2/api/app 404
VM194610:1 Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 0

## Problem
I have tried several import troubleshooting solutions, but import * as wn from 'webnative' > wn.apps.create() or any other method call returns the above error. I am not passing any parameters to any of these methods.

Describe the immediate problem

### Impact

The impact that this bug has

## Solution

Describe the sort of fix that would solve the issue

# Detail

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matheus23** [comment]
Thanks for submitting an issue @ha6755ad!

Unfortunately, I can't reproduce the issue here (at least not with version 0.31.1. I didn't have a chance to test with 0.32 or 0.33 yet, but that part of the code *shouldn't* have changed).

Maybe a couple of questions to get down to the root of the problem:
* Which webnative version are you using?
* What are the parameters are you calling `wn.apps.*` methods with?
* What's the HTTP response body? You can look at that by opening the DevTools in your browser, navigating to the Network tab and finding the request that failed.
