### ISSUE TITLE
`v0.35` issue with `fs.write` — "Could not decode CID"

### ISSUE THREAD

**Issue by nichoth** [fission-codes/webnative#459]
# Summary

The only change was updating to `0.35`, was working previously. Can see the code here: https://github.com/snail-situation/hermes/blob/14f8e5178a0e4e4153177edb43b6ed9feefe3d9e/src/pages/whoami.tsx#L78

## Problem

```js
        try {
            const filepath = wn.path.appData(
                PERMISSIONS.app,
                wn.path.file(CONSTANTS.avatarPath)
            )
            await fs.write(filepath, pendingImage.file)
            console.log('file path written...', filepath)

            // read the file we just wrote
            const content = await fs.cat(filepath)
            appAvatar.value = URL.createObjectURL(
                new Blob([content as BlobPart], { type: 'image/jpeg' })
            )

            await fs.publish()

            setPendingImage(null)
        } catch (err) {
            console.log('could not write file...')
            console.log('errrrrrrrrrrr', err)
        }
```

this is console log:
```
could not write file...
whoami.tsx:68 errrrrrrrrrrr Error: Could not decode CID: {"/":"bafkreicu646jao2xjpkbmk3buom6hmxsexmbwyju22k6wmtnky2ljisv3e"}
    at decodeCID (cid.ts:47:9)
    at PrivateFile.fromInfo (PrivateFile.ts:145:7)
    at PrivateFile.fromLatestName (PrivateFile.ts:117:24)
    at async PrivateTree.getDirectChild (PrivateTree.ts:254:11)
    at async PrivateTree.createOrUpdateChildFile (PrivateTree.ts:191:22)
    at async PrivateTree.addRecurse (tree.ts:82:7)
    at async PrivateTree.add (tree.ts:70:5)
    at async Object.private (filesystem.ts:323:13)
    at async FileSystem.runMutationOnNode (filesystem.ts:762:7)
    at async FileSystem.add (filesystem.ts:312:7)
```

**Comment by nichoth** [comment]
Reproduced in another place — https://github.com/snail-situation/hermes/blob/v0.35/src/pages/whoami.tsx#L114

**Comment by icidasset** [comment]
Thanks @nichoth ! Is this with a file system that existed before and was used with an older version of Webnative? Will look into this tomorrow.

**Comment by nichoth** [comment]
> Thanks @nichoth ! Is this with a file system that existed before and was used with an older version of Webnative? Will look into this tomorrow.

Yes, exactly. The username, `nichoth2` is from the previous version of webnative.

**Comment by icidasset** [comment]
I can't seem to reproduce this when creating a file system in v0.34.2 and then using it in v0.35.2
I assume this error would happen when overriding a private file that was created with v0.34.x (or earlier), but no luck in reproducing it.

I've created a branch for you with something that hopefully might fix it.
You should be able to test that version of Webnative by setting the version string in your `package.json` file to the following:
```json
{
  "webnative": "fission-codes/webnative#icidasset/cid-encoding"
}
```

Some questions for you:
- Did the avatar file actually exist before?
- What about the parent directories?
- Can you override the file in Drive? (make sure that your browser updates Drive, it should say "Downloading update" if you haven't visited Drive since Friday)
- What happens if you delete the parent directory first? Does it work then?

Any additional details you can think of would be very helpful.

**Comment by nichoth** [comment]
Thank you for looking into this.

A few answers:
* yes, the file was written and published in the previous version of wnfs, using identical paths, etc — https://github.com/snail-situation/hermes/blob/main/src/pages/whoami.tsx#L51
* drive didn't load for me. It has been a while since I've used the site, fwiw. I let the page sit for several minutes, and it stayed in this state

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5776508/211408094-e1e8afbb-7904-42f3-bd88-37e314d5f361.png">

-------------

Deleting the parent directory — I'm not sure what that means in this case. The file path is
```js
        const filepath = wn.path.appData(
            PERMISSIONS.app,
            wn.path.file('profile.json')
        )
```

**Comment by nichoth** [comment]
Nevermind, after a few refreshed, drive did load for me. And I deleted the previous avatar.jpg file.

**Comment by nichoth** [comment]
Hmm it seems everything is working now. Mysterious as to the reason why…

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5776508/211409573-08e2cba2-6bbd-418d-9b3a-ffe91f9aeed8.png">

**Comment by icidasset** [comment]
It works now because you deleted the existing file and/or parent directory.

If any other folks come in here, try doing just that.
If it still doesn't work after that, please drop a comment here and we'll try to look into it again.

As always there's the option to completely reset your file system: https://talk.fission.codes/t/how-to-reset-your-filesystem/1875 (may need updating, let us know if this doesn't work for you)
